n_heads:
  type: categorical
  value: [2, 4, 8]

n_layers:
  type: categorical
  value: [2, 4, 8]

interaction_type:
  type: categorical
  value: [0, 1, 2, 3]

max_seq_len:
  type: categorical
  value: [20, 40, 60, 80, 100, 200]

hidden_dim:
  type: categorical
  value: [64, 128, 256]

final_fc_dim:
  type: categorical
  value: [128, 256, 512]

ff_dim:
  type: categorical
  value: [128, 256, 512, 1024, 2048]

partition_question:
  type: categorical
  value: [true, false]

drop_out:
  type: float
  step: 0.1
  value: [0.1, 0.6]

enable_da:
  type: categorical
  value: [true, false]
